language: php

sudo: false

branches:
  only:
    - master

services:
    -mysql

php:
  - 7.4
  - 8.0
  - 8.1

env:
  - WP_VERSION=6.0.2
  - WP_VERSION=6.0.1
  - WP_VERSION=6.0.3
  - WP_VERSION=5.9.4

before_script:
  #- wget https://github.com/woocommerce/woocommerce/archive/refs/tags/6.8.2.tar.gz && tar xf 6.8.2.tar.gz && cp -R woocommerce-6.8.2 ../woocommerce && rm -R woocommerce-6.8.2
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer update
script: vendor/bin/phpunit
