language: php

sudo: false

branches:
  only:
    - master

services:
    -mysql

php:
  - 7.4
  - 8.0
  - 8.1

env:
  - WP_VERSION=6.0.1
  - WP_VERSION=6.0
  - WP_VERSION=5.9.3
  - WP_VERSION=5.9

before_script:
  - wget https://github.com/woocommerce/woocommerce/archive/refs/tags/5.9.0.tar.gz && tar xf 5.9.0.tar.gz && cp -R woocommerce-5.9.0 ../woocommerce && rm -R woocommerce-5.9.0
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer update
script: vendor/bin/phpunit
