language: php

sudo: false

branches:
  only:
    - master

services:
    -mysql

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=5.3
  - WP_VERSION=5.2
  - WP_VERSION=5.1
  - WP_VERSION=5.0
  - WP_VERSION=4.9

matrix:
  exclude:
    - php: 7.4
      env: WP_VERSION=4.9
    - php: 7.3
      env: WP_VERSION=4.9

before_script:
  # - git clone https://github.com/woothemes/woocommerce ../woocommerce
  - wget https://github.com/woocommerce/woocommerce/archive/4.5.1.tar.gz && tar xf 4.5.1.tar.gz && cp -R woocommerce-4.5.1 ../woocommerce && rm -R woocommerce-4.5.1
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer require phpunit/phpunit:">=5.7 <=7.5.20"
  - composer update
script: vendor/bin/phpunit
