language: php

sudo: false

branches:
  only:
    - master

services:
    -mysql

php:
  - 7.3
  - 7.4

env:
  - WP_VERSION=5.8.2
  - WP_VERSION=5.8
  - WP_VERSION=5.7
  - WP_VERSION=5.6
  - WP_VERSION=5.5
  - WP_VERSION=5.4
  - WP_VERSION=5.3
  - WP_VERSION=5.2

matrix:
  exclude:
    - php: 7.4
      env: WP_VERSION=4.9
    - php: 7.4
      env: WP_VERSION=5.0
    - php: 7.4
      env: WP_VERSION=5.1
    - php: 7.4
      env: WP_VERSION=5.2
    - php: 7.4
      env: WP_VERSION=5.3
    - php: 7.3
      env: WP_VERSION=4.9
    - php: 7.3
      env: WP_VERSION=5.0

before_script:
  - wget https://github.com/woocommerce/woocommerce/archive/refs/tags/5.9.0.tar.gz && tar xf 5.9.0.tar.gz && cp -R woocommerce-5.9.0 ../woocommerce && rm -R woocommerce-5.9.0
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer update
script: vendor/bin/phpunit
